apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics
  labels:
    app: logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
        - name: logistics
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user03-logistics:v1
          #image: laios/logistics:1
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
         