server:
  port: 8080
---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Order
          destination: gasstation
          contentType: application/json
        event-out:
          destination: gasstation
          contentType: application/json
          
  #H2콘솔창 http://localhost:8083/h2-console
  h2:
    console:
      enabled: true 
      
  #MongoDB
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/tutorial

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8083
  
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Order
          destination: gasstation
          contentType: application/json
        event-out:
          destination: gasstation
          contentType: application/json
