apiVersion: apps/v1
kind: Deployment
metadata:
  name: station
  labels:
    app: station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station
  template:
    metadata:
      labels:
        app: station
    spec:
      containers:
        - name: station
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user03-station:v1
          #image: laios/station:1
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
       