apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos
  labels:
    app: pos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pos
  template:
    metadata:
      labels:
        app: pos
    spec:
      containers:
        - name: pos
          image: 879772956301.dkr.ecr.ap-northeast-2.amazonaws.com/user03-pos:v1
          #image: laios/pos:1
          #imagePullPolicy: Never
          ports:
            - containerPort: 8080
       